### ISSUE TITLE
Add a link to the Gitter channel on irydium.dev

### ISSUE THREAD

**Issue by wlach** [irydium/irydium#119]
To make the irydium channel on gitter easier to find, we should add a link to the gitter channel:

https://gitter.im/irydium/community

(we may eventually want to encourage people to use matrix instead, but gitter seems like the most sensible default for now as it provides a nicer preview)

We can probably model this PR after the work @m-clare submitted in #115. We may need to add the default fontawesome icons and import something chat related for the image. There's a bunch that would probably work well here:

https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=chat

**Comment by m-clare** [comment]
Closed in #179
