### ISSUE TITLE
Input element changes not reflected

### ISSUE THREAD

**Issue by badboy** [irydium/irydium#230]
It seems that changes to input elements that are bound to a variable don't cause a change anymore.
This can be observed in the [introduction example](https://irydium.dev/examples#introduction).

Changing the dropdown on the "Eviction counts in San Francisco by Year" graph from "Bar" to "Line" does not re-render the graph with the changed variable value anymore.
This used to work.

**Comment by wlach** [comment]
Hmm, yes, this must have broken recently. Will investigate.

**Comment by wlach** [comment]
Forgot to handle cache invalidation when I did up https://github.com/irydium/irydium/pull/222

**Comment by wlach** [comment]
Thanks for the bug report @badboy!

**Comment by badboy** [comment]
Thanks! It's working again
